-- AlterTable
ALTER TABLE "Order" ADD COLUMN "totalCharge" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "discount" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "amountPaid" DECIMAL(10,2) NOT NULL DEFAULT 0;
